// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLux-7O9ABhW1DPxNfewuX_htkeVmfpRA',
    appId: '1:330900117664:web:62ceb5f663ab63ab2b51c5',
    messagingSenderId: '330900117664',
    projectId: 'fir-flutter-codelab-c39c8',
    authDomain: 'fir-flutter-codelab-c39c8.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c39c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrx8O2MK-ccq4D9I-FwlkIBnBmmSJoflY',
    appId: '1:330900117664:android:136dbadbb2f987a32b51c5',
    messagingSenderId: '330900117664',
    projectId: 'fir-flutter-codelab-c39c8',
    storageBucket: 'fir-flutter-codelab-c39c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGaVNw4p-TgzWe_BN0Tw6Ow9YyuQfg5U',
    appId: '1:330900117664:ios:699a6b1f6101541d2b51c5',
    messagingSenderId: '330900117664',
    projectId: 'fir-flutter-codelab-c39c8',
    storageBucket: 'fir-flutter-codelab-c39c8.appspot.com',
    iosClientId: '330900117664-omoer1jflagmbq4hrtq184a65n07mlv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
